### ISSUE TITLE
Further development of json owscontext

### ISSUE THREAD

**Issue by boeckMt** [opengeospatial/owscontext#7]
This repository has not been updated for a long time.
So I'm interested if there any new developments for this Standard and how to use it with clients.

It would also be good to see a list of clients who use this standard.
In my work we have tried to use it [@dlr-eoc/services-ogc](https://github.com/dlr-eoc/ukis-frontend-libraries/tree/master/projects/services-ogc), however we are not sure if it is still used by others and if we should continue to use it

**Comment by jyutzler** [comment]
I'm not sure what to tell you. The standard is not under active development at this time, but it does what it does. I guess my question to you is what open alternative do you have for doing the things OWS Context does? I'm not aware of anything. Your options are pretty much to choose a closed solution, brew your own, or use OWS Context and hope that others will fall in line.

**Comment by mhogeweg** [comment]
As far as clients is concerned, [over at Geoportal Server](https://github.com/Esri/geoportal-server/tree/master/components) we have had an addin for ArcGIS Desktop for years that would allow opening the prior web map context document in ArcMap. More recently (that is, 4 years ago) we also developed a widget for ArcGIS Web AppBuilder that allowed for exporting the map in the app to an OWS Context document. We have not seen a lot of uptake on these or on the use of OWS Context in general. 

Regarding other specs, the Esri Web Map specification is available online as well: https://developers.arcgis.com/web-map-specification/

**Comment by boeckMt** [comment]
Thanks for your answers! As far as I know, there are three possibilities. 
- ows context
- Esri Web Map specification like @mhogeweg mentioned
- Mapbox [Style Specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/).

My idea was more to guide the **ows context** in a direction, so it uses the best things of all three (if that is intended by the inventors?).

I think only if there are a lot of examples and you see that other people use it, then more people will stick to this standard.
And I really would like to have something which is used like GeoJSON (mapping-servers and multiple map-clients can exchange it) to share more the only Features.

So for a map we want like to define:
- Layers and their order
- The status Layers will have (e.g. displayed, transparency)
- The styling for symbols, colors and legends
- Different Sources of Data which layers can use (also including time series data)
- Projections of the Data
- Status of the Map like projection, view, extent, rotation...
- Maybe some generic UI properties which can be extended, so map-clients can draw components for interacting with layers. E.g. should some layers be grouped, or should options like description, legend and controls are displayed on initial loading or hidden)

**Comment by mhogeweg** [comment]
I prefer keeping the information conveyed separate from the application it is viewed in. The web map can be accessed from web applications, mobile, desktop while being rendered the same (styling, visibility, etc all are included in the web map), but giving the functional capabilities of ArcGIS Pro vs ArcGIS Dashboard vs generic viewers through those applications.

**Comment by boeckMt** [comment]
@mhogeweg you're right, there shouldn't be any information custom to some special clients (application it is viewed in) in general.
For this we have to find a generic solution, which fits to most of the clients. Custom parts are then an extension as in the current implementation of the `owscontext`.
